### ISSUE TITLE
Forward jump segfaults when encountering whitespace

### ISSUE THREAD

**Issue by daviewales** [satornine/project-midnight#3]
Forward jump segfaults when encountering whitespace

Here is some sample code:

    pipes `Testing jump`

    jump <far
    pipes `This shouldn't print`
    jump >far

    pipes `This should print`

    jump <more-far

    pipes `This shouldn't print either`

    ~ Whitespace seems to break forward jumps

    jump >more-far

    pipes `This should print`

**Comment by satornine** [comment]
Stop complaining about trivial things.

**Comment by satornine** [comment]
Fixed in untested

**Comment by daviewales** [comment]
Fixed in 24dfcb9389978ad3d6031a2f04bdc7ae85a4eab1
