### ISSUE TITLE
less subcommand doesn't work

### ISSUE THREAD

**Issue by daviewales** [satornine/project-midnight#4]
Here is some code that demonstrates the problem:

    pipes `Testing the less command`

    pipes 5 >a
    pipes 6 >b

    pipes 0 >count
    jump >loop1
    if less <a <b
    pipes <a ` is less than ` <b
    else
    pipes <a ` is greater than or equal to ` <b
    jump

    pipes ^a 1
    pipes ^count 1
    greater 3 <count
    jump <loop1

**Comment by satornine** [comment]
Fixed in untested. Not copying number like David said.

**Comment by daviewales** [comment]
Fixed here: b3e172752fe1625ad90eef8f8bb1bb3e49a79591
